version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672" # RabbitMQ management console's port
      - "5672:5672" # The standard AMQP protocol port
    networks:
      - default
      - flight_search_microservices

networks:
  flight_search_microservices:
    external:
      name: flight_search_microservices